# .github/workflows/release-docker.yml
name: Publish Docker image
on:
  push:
    tags: ["v*.*.*"]        # every semantic-version tag
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mongodb/kingfisher:latest
            ghcr.io/mongodb/kingfisher:${{ github.ref_name }}
